from database import Database

db = Database()
# db.add_task("Hyy")
# db.add_task("HLO")
# db.add_task("HY")
# db.add_task("HLL")
# db.complete_task(2)
# db.complete_task(5)
# db.complete_task(9)
# db.complete_task(3)
# print(db.get_tasks())
# db.add_note("hlo")
# db.add_note("hYY")
db.get_task_stats()